name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DockerhubUser }}
        password: ${{ secrets.DockerhubPass }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag synerynx/redeemalliantcashback:1.0.${{ github.run_number }} --tag synerynx/redeemalliantcashback:latest
    - name: Push
      run: docker push synerynx/redeemalliantcashback:1.0.${{ github.run_number }}
    - name: Push latest
      run: docker push synerynx/redeemalliantcashback:latest
